version: "3.8"

services:
  app:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./server:/server
      - /server/node_modules
    restart: on-failure
    command: >
      sh -c "npm start"

  db:
    image: mongo
    env_file:
      - .env
    volumes:
      - ./mongo_db:/data/db
      - ./mongo-init.js:/docker_entrypoint-initdb.d/mongo-init.js:ro
    restart: on-failure

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./web:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf