export * from './HomePage'
export * from './AboutUsPage'
export * from './NovunkuPage'
export * from './AdminPage'
export * from './RegisterPage'
export * from './LogInPage'
export * from './OrderPage'
