export * from './categories.slice'
export * from './products.slice'
export * from './types.slice'
export * from './users.slice'
export * from './auth.slice'
export * from './basket.slice'
export * from './order.slice'
export * from './news.slice'